### ISSUE TITLE
ArxmlLexer fails on XML comments containing ">"

### ISSUE THREAD

**Issue by EdVanDance** [DanielT/autosar-data#15]
Hello.

We are facing an `InvalidComment` issue while loading some 3rd party arxmls containing `<` / `>` in comments.

It seems like the lexer does not accept comments as specified by: https://www.w3.org/TR/xml/#sec-comments

I added a test locally to verify:
```rust
    #[test]
    fn test_w3c_comment_example() {
        let data = b"<!-- declarations for <head> & <body> -->";
        let mut lexer = ArxmlLexer::new(data, PathBuf::from("(buffer)"));
        assert!(matches!(lexer.next(), Ok((_, ArxmlEvent::Comment(_)))));
    }

```

It fails.

**Comment by DanielT** [comment]
Thanks for the report!

Including the testcase was very useful, I've committed it with the fix.

**Comment by EdVanDance** [comment]
Well, that was quick 😄 

Thank you very much 👍
