### ISSUE TITLE
"Attempt to subtract with overflow" in trim_byte_string(...)

### ISSUE THREAD

**Issue by nijakow** [DanielT/autosar-data#2]
Hi, I just found a bug in `trim_byte_string(input: &[u8]) -> &[u8]` [here](https://github.com/DanielT/autosar-data/blob/8e18185393e761362cc8eb6cf6fba4aa244bcf07/autosar-data/src/parser.rs#L718) in `parser.rs`.

For me, parsing some AUTOSAR files leads to an "attempt to subtract with overflow" - which implies that you haven't protected the function against zero-length strings.

I'd suggest adding a zero-length check.

**Comment by DanielT** [comment]
Thanks for the bug report.
I just committed a fix
