### ISSUE TITLE
Feature request: Serialize element without nested identifiable elements

### ISSUE THREAD

**Issue by christianhecht86** [DanielT/autosar-data#22]
Hello Daniel,

I like to have a little change in the serialize method of elements:

For sub elements (and nested) of the element, the serialize method was called,  identifiable elements shall be ignored.

Usecase:

I like to compare big ARXML files. The idea is to split the big file in smaller once; create for each identifiable element a separate file and use a text based compare tool like beyond compare to compare all files.

I loop over each element and write each identifiable element into a separate file. 
But for elements, having nested identifiable element, the elements are generated twice.

Proposal:

- new method in elements "serialize_without_nested_identifiables"
- add flag to without_nested_identifiables to serialize_internal
- skip call of "subelem.serialize_internal(outstring, indent + 1, false, for_file);" if without_nested_identifiables is true

example for creation of file snippets:

```
    let ar_model = AutosarModel::new();

    ar_model
        .load_file(input_file_name, false)
        .expect("Unable to load file");

    ar_model.sort();

    //iterate over all model elements
    for (_, element) in ar_model.elements_dfs() {
        if element.is_identifiable() && element.element_name() != ElementName::ArPackage {
            let ar_path = element.path().unwrap();

            let parts: Vec<_> = ar_path.split('/').collect();

            let dir_path = format!("{}/{}", output_dir, parts[1..parts.len() - 1].join("/"));
            let file_name = format!("{}.arxml", parts[parts.len() - 1]);
            let file_path = format!("{}/{}", dir_path, file_name);

            fs::create_dir_all(&dir_path).expect("Unable to create dir");

            let content = element.serialize();
            fs::write(file_path, &content).expect("Unable to write file");
        }
    }
```

Thanks

Christian

**Comment by DanielT** [comment]
Hello,

What you propose is already possible with the existing API. You can add each identifiable element to a new file, and then write the model.

```rust
use autosar_data::*;

fn main() {
    let args = std::env::args().collect::<Vec<String>>();
    if args.len() != 2 {
        eprintln!("Usage: {} <path/to/autosar.arxml>", args[0]);
        std::process::exit(1);
    }

    let model = AutosarModel::new();
    let (base_file, _) = model.load_file(&args[1], false).unwrap();
    let version = base_file.version();

    // iterate over all identifiable elements in the model
    for (path, weakelem) in model.identifiable_elements() {
        if let Some(elem) = weakelem.upgrade() {
            // create a new file for each element
            let filename = path_to_filename(&path);
            let subfile = model.create_file(filename, version).unwrap();
            elem.add_to_file(&subfile).unwrap();

            // the element is initially also part of every file that contains its parent elements
            // remove it from all of those
            for weak_file in elem.file_membership().unwrap().1 {
                if let Some(f) = weak_file.upgrade() {
                    if f != subfile {
                        elem.remove_from_file(&f).unwrap();
                    }
                }
            }
        }
    }
    // make sure we don't overwrite the original file
    model.remove_file(&base_file);
    // write the new files to disk
    model.write().unwrap();
}

fn path_to_filename(path: &str) -> String {
    // remove the leading slash and replace the rest with underscores to make a valid filename from the Autosar path
    // e.g. /Ecus/Ecu_A/CanController -> Ecus_Ecu_A_CanController.arxml
    let mut filename = path[1..].replace("/", "_");
    filename.push_str(".arxml");
    filename
}
```

**Comment by christianhecht86** [comment]
Hi Daniel,

thanks. This solution helps me a lot.

But on a bigger file, a got a FilesetModificationForbidden error. Short-Name duplications I can rule out.

It seems to have something to do with I-SIGNAL-TO-I-PDU-MAPPINGs of NM-PDUs (autosar_4-3-0.xsd).

```
<NM-PDU>
  <SHORT-NAME>PDU_NAME</SHORT-NAME>
  <LENGTH>8</LENGTH>
  <I-SIGNAL-TO-I-PDU-MAPPINGS>
	<I-SIGNAL-TO-I-PDU-MAPPING>
	  <SHORT-NAME>SIGNAL_NAME</SHORT-NAME>
	  <I-SIGNAL-REF DEST="I-SIGNAL">/ISignal/SIGNAL_NAME_PDU_NAME</I-SIGNAL-REF>
	  <PACKING-BYTE-ORDER>MOST-SIGNIFICANT-BYTE-LAST</PACKING-BYTE-ORDER>
	  <START-POSITION>12</START-POSITION>
	  <TRANSFER-PROPERTY>TRIGGERED</TRANSFER-PROPERTY>
	</I-SIGNAL-TO-I-PDU-MAPPING>
...
  </I-SIGNAL-TO-I-PDU-MAPPINGS>
  <UNUSED-BIT-PATTERN>0</UNUSED-BIT-PATTERN>
</NM-PDU>

```


Do you have a tip on what I could try out?

Christian

**Comment by DanielT** [comment]
The functions `add_to_file` and `remove_from_file` can only assign an element to a file if the parent has the attribute "splittable" in the meta model.

I assumed that all parents of identifiable elements were splittable, but this was clearly wrong.
You can modify the example code to check this before calling either of those functions like this:

```rust
let parent = elem.parent().unwrap().unwrap();
if parent.element_type().splittable_in(version) {
    // create the new file, assign the element, etc.
}
```

Even then the code is definitely "demo code", which could still fail in other ways, for example with duplicate filenames:
If your file contains the elements `/A/B` and `/A_B` , then the elements `/A/B` and `/A_B` will both try to use the same filename: `A_B.arxml`.

**Comment by christianhecht86** [comment]
Thanks, for the explanation. No it worked.
