### ISSUE TITLE
XML parser: single-quote delimited attribute values silently lost

### ISSUE THREAD

**Issue by FlTr** [DanielT/autosar-data#23]
Attributes with their values delimited in single-quotes are lost during loading files. They neither appear in the loaded model nor when serialized again.

```xml
<DEFINITION-REF DEST="ECUC-MODULE-DEF">/AUTOSAR_A</DEFINITION-REF>
```
versus
```xml
<DEFINITION-REF DEST='ECUC-MODULE-DEF'>/AUTOSAR_A</DEFINITION-REF>
```

As of xml specification, single quotes are allowed.

> Definition: the content of the [AttValue](https://www.w3.org/TR/xml/#NT-AttValue) (the text between the ' or " delimiters) as the attribute value.

https://www.w3.org/TR/xml/#sec-starttags
https://www.w3.org/TR/xml/#NT-AttValue

**Comment by DanielT** [comment]
Thanks for the bug report!

The fact that attributes in single quotes didn't work is clearly a bug, though I've never seen a file that was written that way.
I also dislike the fact that it failed silently.

I have fixed both in the commit I just pushed.
