### ISSUE TITLE
Loosing attribute due to number of spaces

### ISSUE THREAD

**Issue by FlTr** [DanielT/autosar-data#25]
The fix #23 introduced another behavior regarding parsing attributes. If there is more than one space between xml tag and attribute (maybe also between attributes), the attribute is lost.

E.g. 2 spaces between tag and first attribute. _xml:space_ is not present in model / serialized file.
```xml
<L-5  xml:space="default" L="EN">
```

Having just a single space, everything is fine.
```xml
<L-5 xml:space="default" L="EN">
```

https://www.w3.org/TR/xml/#NT-S

Besides reporting bug by bug.
Great project, great support!

**Comment by DanielT** [comment]
Thanks

Very annoying that I didn't think of this case, so I lacked both code to handle it and a unit test for it.
At least it was trivial to fix...
