### ISSUE TITLE
Add features to limit supported autosar versions?

### ISSUE THREAD

**Issue by shahn** [DanielT/autosar-data#26]
autosar-data takes quite a bit of time to compile. I would be happy to investigate adding a feature for each autosar release it supports, and a default feature to support them all so there's no user-observable change in default behaviour. I guess this would happen via a patch to https://github.com/DanielT/autosar-xsd-mangler.

In addition, the num-derive dependency for autosar-data-specification could likely be removed very easily, cutting the compile time further as autosar-data-specification could be compiled in parallel to syn.

Would you be open to such changes?

**Comment by DanielT** [comment]
Certainly.
I'm not sure it will work, but if you can make it happen, then I'll integrate it.
Removing num-derive looks like a much easier win.

**Comment by shahn** [comment]
Ah yes, I see your concern - you'd basically want to limit which autosar xsd files you're merging, and you'd need to annotate which versions of autosar something appears in. That seems probably not worth it.

**Comment by shahn** [comment]
Thanks for merging the change, it reduced build time quite measurably for such a quick fix.
